include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  # In addition to the flutter_lints
  rules:
    - always_declare_return_types
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - flutter_style_todos
    - hash_and_equals
    - non_constant_identifier_names
    - package_api_docs
    - package_prefixed_library_names
    - prefer_single_quotes
    - sort_child_properties_last
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_statements
    - unsafe_html
