blank_issues_enabled: false
contact_links:
  - name: Flutter issue
    url: https://github.com/flutter/flutter/issues/new/choose
    about: I'm having an issue with Flutter itself.
  - name: Question
    url: https://stackoverflow.com/questions/tagged/flutter?tab=Frequent
    about: I have a question about Flutter.
