name: gallery_devicelab

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  args:
  meta:
  logging:
  path:
  pedantic:
  platform:
  process:
  shelf:
  shelf_static:
  stack_trace:
  vm_service_client:
  webkit_inspection_protocol:
  yaml:
