// Generated by package:flutter_messages

import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:messages/package_intl_object.dart';

import 'intl_en.g.dart';

class GalleryLocalizations {
  static Iterable<LocalizationsDelegate<dynamic>> localizationsDelegates = [
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static LocalizationsDelegate<GalleryMessages> delegate =
      GalleryLocalizationsDelegate();

  static List<Locale> get supportedLocales {
    return GalleryMessages.knownLocales.map((e) {
      var split = e.split('_');
      var code = split.length > 1 ? split[1] : null;
      return Locale(split.first, code);
    }).toList();
  }

  static GalleryMessages? of(BuildContext context) =>
      Localizations.of<GalleryMessages>(context, GalleryMessages);
}

class GalleryLocalizationsDelegate
    extends LocalizationsDelegate<GalleryMessages> {
  @override
  bool isSupported(Locale locale) =>
      GalleryMessages.knownLocales.contains(locale.toString());

  @override
  Future<GalleryMessages> load(Locale locale) async {
    await messages.loadLocale(locale.toString());
    return messages;
  }

  @override
  bool shouldReload(LocalizationsDelegate<GalleryMessages> old) => false;
}

GalleryMessages messages =
    GalleryMessages(rootBundle.loadString, const OldIntlObject());
