// Generated by package:messages_builder

import 'package:messages/messages_json.dart';

class GalleryMessages {
  GalleryMessages(
    this._fileLoader,
    this.intlObject,
  );

  final Future<String> Function(String id) _fileLoader;

  String _currentLocale = 'en';

  final Map<String, MessageList> _messages = {};

  static const carbs = {
    'es_NI': ('lib/l10n/intl_es_NI.json', 'I2tfNstx'),
    'bs': ('lib/l10n/intl_bs.json', 'LTRM2Q7S'),
    'de': ('lib/l10n/intl_de.json', 'WKJQhq7b'),
    'cy': ('lib/l10n/intl_cy.json', 'gSCfH59E'),
    'zh_CN': ('lib/l10n/intl_zh_CN.json', 'y+iGUGT5'),
    'de_CH': ('lib/l10n/intl_de_CH.json', 'WKJQhq7b'),
    'es_PA': ('lib/l10n/intl_es_PA.json', 'I2tfNstx'),
    'fr_CA': ('lib/l10n/intl_fr_CA.json', 'wKDTm6DN'),
    'da': ('lib/l10n/intl_da.json', '6czMLGyj'),
    'en_CA': ('lib/l10n/intl_en_CA.json', 'GsYf7vpw'),
    'zh': ('lib/l10n/intl_zh.json', 'y+iGUGT5'),
    'ar_SA': ('lib/l10n/intl_ar_SA.json', 'FyioriJW'),
    'ar_EG': ('lib/l10n/intl_ar_EG.json', 'FyioriJW'),
    'fi': ('lib/l10n/intl_fi.json', 'Wk4B9bBc'),
    'pt': ('lib/l10n/intl_pt.json', 'fWK9mBo+'),
    'ta': ('lib/l10n/intl_ta.json', 'Yv/kWFH/'),
    'es_MX': ('lib/l10n/intl_es_MX.json', 'I2tfNstx'),
    'bn': ('lib/l10n/intl_bn.json', 'd3fLOhJn'),
    'es_AR': ('lib/l10n/intl_es_AR.json', 'I2tfNstx'),
    'ne': ('lib/l10n/intl_ne.json', 'u8EvLOPG'),
    'si': ('lib/l10n/intl_si.json', '8J6udMMu'),
    'en_NZ': ('lib/l10n/intl_en_NZ.json', 'Jw9AYCQe'),
    'he': ('lib/l10n/intl_he.json', 'VYx6VXuq'),
    'ja': ('lib/l10n/intl_ja.json', 'jLnfX7Kt'),
    'az': ('lib/l10n/intl_az.json', 'd/AEJ7Sw'),
    'nl': ('lib/l10n/intl_nl.json', 'jDTZ3Z23'),
    'sv': ('lib/l10n/intl_sv.json', 'S/hYx1ge'),
    'ky': ('lib/l10n/intl_ky.json', 'npL0V0Qt'),
    'fr': ('lib/l10n/intl_fr.json', '/IWgh7kg'),
    'es_CL': ('lib/l10n/intl_es_CL.json', 'I2tfNstx'),
    'zh_TW': ('lib/l10n/intl_zh_TW.json', 'MYkj+adl'),
    'es_PR': ('lib/l10n/intl_es_PR.json', 'I2tfNstx'),
    'lt': ('lib/l10n/intl_lt.json', 'JBLd+/LO'),
    'as': ('lib/l10n/intl_as.json', '7RaJP5fI'),
    'pt_PT': ('lib/l10n/intl_pt_PT.json', '3jFSW6Ax'),
    'en_ZA': ('lib/l10n/intl_en_ZA.json', 'Jw9AYCQe'),
    'en_AU': ('lib/l10n/intl_en_AU.json', 'Jw9AYCQe'),
    'es_CR': ('lib/l10n/intl_es_CR.json', 'I2tfNstx'),
    'mk': ('lib/l10n/intl_mk.json', '+9y2sbeO'),
    'el': ('lib/l10n/intl_el.json', '+kYGmdZf'),
    'es_DO': ('lib/l10n/intl_es_DO.json', 'I2tfNstx'),
    'it': ('lib/l10n/intl_it.json', '5A8EVbkc'),
    'en_IN': ('lib/l10n/intl_en_IN.json', 'Jw9AYCQe'),
    'ur': ('lib/l10n/intl_ur.json', 'u0/y0K/W'),
    'de_AT': ('lib/l10n/intl_de_AT.json', 'WKJQhq7b'),
    'es_US': ('lib/l10n/intl_es_US.json', 'I2tfNstx'),
    'am': ('lib/l10n/intl_am.json', 'QxwSrcAr'),
    'sw': ('lib/l10n/intl_sw.json', 'Q8dgKlTi'),
    'ar': ('lib/l10n/intl_ar.json', 'FyioriJW'),
    'lv': ('lib/l10n/intl_lv.json', 'nFWcv1Pt'),
    'ru': ('lib/l10n/intl_ru.json', 'BKLMLBzw'),
    'en_SG': ('lib/l10n/intl_en_SG.json', 'Jw9AYCQe'),
    'es_SV': ('lib/l10n/intl_es_SV.json', 'I2tfNstx'),
    'vi': ('lib/l10n/intl_vi.json', '/ycTb70e'),
    'ar_JO': ('lib/l10n/intl_ar_JO.json', 'FyioriJW'),
    'kk': ('lib/l10n/intl_kk.json', 'w5KJaSeF'),
    'ca': ('lib/l10n/intl_ca.json', 'zPshDy/u'),
    'es_CO': ('lib/l10n/intl_es_CO.json', 'I2tfNstx'),
    'is': ('lib/l10n/intl_is.json', '/uOjfvJe'),
    'or': ('lib/l10n/intl_or.json', 'oUFt3LA0'),
    'be': ('lib/l10n/intl_be.json', '2xf9i0QN'),
    'et': ('lib/l10n/intl_et.json', 'dAlPn8j4'),
    'sk': ('lib/l10n/intl_sk.json', 'cTnXNMP+'),
    'eu': ('lib/l10n/intl_eu.json', 'kLgdhlbF'),
    'ka': ('lib/l10n/intl_ka.json', 'rKRPFKcu'),
    'ko': ('lib/l10n/intl_ko.json', 'kclz5kfA'),
    'es_UY': ('lib/l10n/intl_es_UY.json', 'I2tfNstx'),
    'mn': ('lib/l10n/intl_mn.json', 'e5zXoM5k'),
    'hu': ('lib/l10n/intl_hu.json', '+52ys80A'),
    'sq': ('lib/l10n/intl_sq.json', 'p0uWK4jS'),
    'es_EC': ('lib/l10n/intl_es_EC.json', 'I2tfNstx'),
    'en_IE': ('lib/l10n/intl_en_IE.json', 'Jw9AYCQe'),
    'tl': ('lib/l10n/intl_tl.json', 'bfjEUO/2'),
    'gu': ('lib/l10n/intl_gu.json', 'GPEJuqCw'),
    'hy': ('lib/l10n/intl_hy.json', 'HFdTDN35'),
    'fa': ('lib/l10n/intl_fa.json', '2Ma4Y7jn'),
    'es_BO': ('lib/l10n/intl_es_BO.json', 'I2tfNstx'),
    'te': ('lib/l10n/intl_te.json', 'iW9mkYWz'),
    'sr': ('lib/l10n/intl_sr.json', 'lt92eIcf'),
    'ml': ('lib/l10n/intl_ml.json', '4njd7bH4'),
    'pt_BR': ('lib/l10n/intl_pt_BR.json', 'fWK9mBo+'),
    'gl': ('lib/l10n/intl_gl.json', 'G2aV0BzN'),
    'mr': ('lib/l10n/intl_mr.json', 's/81I4oU'),
    'id': ('lib/l10n/intl_id.json', 'RUiSlQuJ'),
    'zu': ('lib/l10n/intl_zu.json', 'NM4/fZYH'),
    'th': ('lib/l10n/intl_th.json', 'MBHflpHI'),
    'cs': ('lib/l10n/intl_cs.json', 'on6NLVd5'),
    'kn': ('lib/l10n/intl_kn.json', '+EQKCd3H'),
    'sr_Latn': ('lib/l10n/intl_sr_Latn.json', 'A6aFTGSG'),
    'pa': ('lib/l10n/intl_pa.json', 'XOOVHeBh'),
    'ro': ('lib/l10n/intl_ro.json', 'kuv6RzgN'),
    'gsw': ('lib/l10n/intl_gsw.json', 'WKJQhq7b'),
    'tr': ('lib/l10n/intl_tr.json', 'UVQKcn1D'),
    'zh_HK': ('lib/l10n/intl_zh_HK.json', 'YW6QxEWb'),
    'es_VE': ('lib/l10n/intl_es_VE.json', 'I2tfNstx'),
    'es_HN': ('lib/l10n/intl_es_HN.json', 'I2tfNstx'),
    'ms': ('lib/l10n/intl_ms.json', 'PZRVg74v'),
    'en': ('lib/l10n/intl_en.json', 'UOhEi6IF'),
    'nb': ('lib/l10n/intl_nb.json', 'M8x1QjoG'),
    'my': ('lib/l10n/intl_my.json', 'FnDHVCPc'),
    'ar_MA': ('lib/l10n/intl_ar_MA.json', 'FyioriJW'),
    'km': ('lib/l10n/intl_km.json', 'Eynj72u2'),
    'es_PY': ('lib/l10n/intl_es_PY.json', 'I2tfNstx'),
    'sl': ('lib/l10n/intl_sl.json', '2uxFYI5W'),
    'en_GB': ('lib/l10n/intl_en_GB.json', 'Jw9AYCQe'),
    'pl': ('lib/l10n/intl_pl.json', 'uLzHc4NY'),
    'fil': ('lib/l10n/intl_fil.json', 'bfjEUO/2'),
    'es_PE': ('lib/l10n/intl_es_PE.json', 'I2tfNstx'),
    'uk': ('lib/l10n/intl_uk.json', 'SSt2Tq3y'),
    'lo': ('lib/l10n/intl_lo.json', 'baHS1uOf'),
    'hi': ('lib/l10n/intl_hi.json', 'XBi6M9RQ'),
    'hr': ('lib/l10n/intl_hr.json', 'sxkQGfZx'),
    'es_419': ('lib/l10n/intl_es_419.json', 'I2tfNstx'),
    'uz': ('lib/l10n/intl_uz.json', 'qT6C/2ev'),
    'es': ('lib/l10n/intl_es.json', 'jvocrh6N'),
    'bg': ('lib/l10n/intl_bg.json', 'Z7x1912G'),
    'es_GT': ('lib/l10n/intl_es_GT.json', 'I2tfNstx'),
    'af': ('lib/l10n/intl_af.json', 'jnwZXTC3'),
    'fr_CH': ('lib/l10n/intl_fr_CH.json', '/IWgh7kg')
  };

  IntlObject intlObject;

  String get currentLocale => _currentLocale;

  MessageList get _currentMessages => _messages[currentLocale]!;

  static Iterable<String> get knownLocales => carbs.keys;

  Future<void> loadLocale(String locale) async {
    if (!_messages.containsKey(locale)) {
      final info = carbs[locale];
      final carb = info?.$1;
      if (carb == null) {
        throw ArgumentError('Locale $locale is not in $knownLocales');
      }
      final data = await _fileLoader(carb);
      final messageList = MessageListJson.fromString(data, intlObject);
      if (messageList.preamble.hash != info?.$2) {
        throw ArgumentError('''
              Messages file for locale $locale has different hash "${messageList.preamble.hash}" than generated code "${info?.$2}".''');
      }
      _messages[locale] = messageList;
    }
    _currentLocale = locale;
  }

  void loadAllLocales() {
    for (var locale in knownLocales) {
      loadLocale(locale);
    }
  }

  String aboutDialogDescription(String repoLink) =>
      _currentMessages.generateStringAtIndex(0, [repoLink]);

  String get backToGallery => _currentMessages.generateStringAtIndex(1, []);

  String get bannerDemoLeadingText =>
      _currentMessages.generateStringAtIndex(2, []);

  String get bannerDemoMultipleText =>
      _currentMessages.generateStringAtIndex(3, []);

  String get bannerDemoResetText =>
      _currentMessages.generateStringAtIndex(4, []);

  String get bannerDemoText => _currentMessages.generateStringAtIndex(5, []);

  String get bottomAppBar => _currentMessages.generateStringAtIndex(6, []);

  String get bottomAppBarNotch => _currentMessages.generateStringAtIndex(7, []);

  String get bottomAppBarPosition =>
      _currentMessages.generateStringAtIndex(8, []);

  String get bottomAppBarPositionDockedCenter =>
      _currentMessages.generateStringAtIndex(9, []);

  String get bottomAppBarPositionDockedEnd =>
      _currentMessages.generateStringAtIndex(10, []);

  String get bottomAppBarPositionFloatingCenter =>
      _currentMessages.generateStringAtIndex(11, []);

  String get bottomAppBarPositionFloatingEnd =>
      _currentMessages.generateStringAtIndex(12, []);

  String get bottomNavigationAccountTab =>
      _currentMessages.generateStringAtIndex(13, []);

  String get bottomNavigationAlarmTab =>
      _currentMessages.generateStringAtIndex(14, []);

  String get bottomNavigationCalendarTab =>
      _currentMessages.generateStringAtIndex(15, []);

  String get bottomNavigationCameraTab =>
      _currentMessages.generateStringAtIndex(16, []);

  String get bottomNavigationCommentsTab =>
      _currentMessages.generateStringAtIndex(17, []);

  String bottomNavigationContentPlaceholder(String title) =>
      _currentMessages.generateStringAtIndex(18, [title]);

  String get buttonText => _currentMessages.generateStringAtIndex(19, []);

  String get buttonTextCreate => _currentMessages.generateStringAtIndex(20, []);

  String get cardsDemoExplore => _currentMessages.generateStringAtIndex(21, []);

  String cardsDemoExploreSemantics(String destinationName) =>
      _currentMessages.generateStringAtIndex(22, [destinationName]);

  String cardsDemoShareSemantics(String destinationName) =>
      _currentMessages.generateStringAtIndex(23, [destinationName]);

  String get cardsDemoTappable =>
      _currentMessages.generateStringAtIndex(24, []);

  String get cardsDemoTravelDestinationCity1 =>
      _currentMessages.generateStringAtIndex(25, []);

  String get cardsDemoTravelDestinationCity2 =>
      _currentMessages.generateStringAtIndex(26, []);

  String get cardsDemoTravelDestinationDescription1 =>
      _currentMessages.generateStringAtIndex(27, []);

  String get cardsDemoTravelDestinationDescription2 =>
      _currentMessages.generateStringAtIndex(28, []);

  String get cardsDemoTravelDestinationDescription3 =>
      _currentMessages.generateStringAtIndex(29, []);

  String get cardsDemoTravelDestinationLocation1 =>
      _currentMessages.generateStringAtIndex(30, []);

  String get cardsDemoTravelDestinationLocation2 =>
      _currentMessages.generateStringAtIndex(31, []);

  String get cardsDemoTravelDestinationTitle1 =>
      _currentMessages.generateStringAtIndex(32, []);

  String get cardsDemoTravelDestinationTitle2 =>
      _currentMessages.generateStringAtIndex(33, []);

  String get cardsDemoTravelDestinationTitle3 =>
      _currentMessages.generateStringAtIndex(34, []);

  String get chipBiking => _currentMessages.generateStringAtIndex(35, []);

  String get chipElevator => _currentMessages.generateStringAtIndex(36, []);

  String get chipFireplace => _currentMessages.generateStringAtIndex(37, []);

  String get chipLarge => _currentMessages.generateStringAtIndex(38, []);

  String get chipMedium => _currentMessages.generateStringAtIndex(39, []);

  String get chipSmall => _currentMessages.generateStringAtIndex(40, []);

  String get chipTurnOnLights => _currentMessages.generateStringAtIndex(41, []);

  String get chipWasher => _currentMessages.generateStringAtIndex(42, []);

  String get colorsAmber => _currentMessages.generateStringAtIndex(43, []);

  String get colorsBlue => _currentMessages.generateStringAtIndex(44, []);

  String get colorsBlueGrey => _currentMessages.generateStringAtIndex(45, []);

  String get colorsBrown => _currentMessages.generateStringAtIndex(46, []);

  String get colorsCyan => _currentMessages.generateStringAtIndex(47, []);

  String get colorsDeepOrange => _currentMessages.generateStringAtIndex(48, []);

  String get colorsDeepPurple => _currentMessages.generateStringAtIndex(49, []);

  String get colorsGreen => _currentMessages.generateStringAtIndex(50, []);

  String get colorsGrey => _currentMessages.generateStringAtIndex(51, []);

  String get colorsIndigo => _currentMessages.generateStringAtIndex(52, []);

  String get colorsLightBlue => _currentMessages.generateStringAtIndex(53, []);

  String get colorsLightGreen => _currentMessages.generateStringAtIndex(54, []);

  String get colorsLime => _currentMessages.generateStringAtIndex(55, []);

  String get colorsOrange => _currentMessages.generateStringAtIndex(56, []);

  String get colorsPink => _currentMessages.generateStringAtIndex(57, []);

  String get colorsPurple => _currentMessages.generateStringAtIndex(58, []);

  String get colorsRed => _currentMessages.generateStringAtIndex(59, []);

  String get colorsTeal => _currentMessages.generateStringAtIndex(60, []);

  String get colorsYellow => _currentMessages.generateStringAtIndex(61, []);

  String get craneDescription => _currentMessages.generateStringAtIndex(62, []);

  String get craneEat => _currentMessages.generateStringAtIndex(63, []);

  String get craneEat0 => _currentMessages.generateStringAtIndex(64, []);

  String get craneEat0SemanticLabel =>
      _currentMessages.generateStringAtIndex(65, []);

  String get craneEat1 => _currentMessages.generateStringAtIndex(66, []);

  String get craneEat10 => _currentMessages.generateStringAtIndex(67, []);

  String get craneEat10SemanticLabel =>
      _currentMessages.generateStringAtIndex(68, []);

  String get craneEat1SemanticLabel =>
      _currentMessages.generateStringAtIndex(69, []);

  String get craneEat2 => _currentMessages.generateStringAtIndex(70, []);

  String get craneEat2SemanticLabel =>
      _currentMessages.generateStringAtIndex(71, []);

  String get craneEat3 => _currentMessages.generateStringAtIndex(72, []);

  String get craneEat3SemanticLabel =>
      _currentMessages.generateStringAtIndex(73, []);

  String get craneEat4 => _currentMessages.generateStringAtIndex(74, []);

  String get craneEat4SemanticLabel =>
      _currentMessages.generateStringAtIndex(75, []);

  String get craneEat5 => _currentMessages.generateStringAtIndex(76, []);

  String get craneEat5SemanticLabel =>
      _currentMessages.generateStringAtIndex(77, []);

  String get craneEat6 => _currentMessages.generateStringAtIndex(78, []);

  String get craneEat6SemanticLabel =>
      _currentMessages.generateStringAtIndex(79, []);

  String get craneEat7 => _currentMessages.generateStringAtIndex(80, []);

  String get craneEat7SemanticLabel =>
      _currentMessages.generateStringAtIndex(81, []);

  String get craneEat8 => _currentMessages.generateStringAtIndex(82, []);

  String get craneEat8SemanticLabel =>
      _currentMessages.generateStringAtIndex(83, []);

  String get craneEat9 => _currentMessages.generateStringAtIndex(84, []);

  String get craneEat9SemanticLabel =>
      _currentMessages.generateStringAtIndex(85, []);

  String craneEatRestaurants(int totalRestaurants) =>
      _currentMessages.generateStringAtIndex(86, [totalRestaurants]);

  String get craneEatSubhead => _currentMessages.generateStringAtIndex(87, []);

  String craneFlightDuration(
    String hoursShortForm,
    String minutesShortForm,
  ) =>
      _currentMessages
          .generateStringAtIndex(88, [hoursShortForm, minutesShortForm]);

  String get craneFly => _currentMessages.generateStringAtIndex(89, []);

  String get craneFly0 => _currentMessages.generateStringAtIndex(90, []);

  String get craneFly0SemanticLabel =>
      _currentMessages.generateStringAtIndex(91, []);

  String get craneFly1 => _currentMessages.generateStringAtIndex(92, []);

  String get craneFly10 => _currentMessages.generateStringAtIndex(93, []);

  String get craneFly10SemanticLabel =>
      _currentMessages.generateStringAtIndex(94, []);

  String get craneFly11 => _currentMessages.generateStringAtIndex(95, []);

  String get craneFly11SemanticLabel =>
      _currentMessages.generateStringAtIndex(96, []);

  String get craneFly12 => _currentMessages.generateStringAtIndex(97, []);

  String get craneFly12SemanticLabel =>
      _currentMessages.generateStringAtIndex(98, []);

  String get craneFly13 => _currentMessages.generateStringAtIndex(99, []);

  String get craneFly13SemanticLabel =>
      _currentMessages.generateStringAtIndex(100, []);

  String get craneFly1SemanticLabel =>
      _currentMessages.generateStringAtIndex(101, []);

  String get craneFly2 => _currentMessages.generateStringAtIndex(102, []);

  String get craneFly2SemanticLabel =>
      _currentMessages.generateStringAtIndex(103, []);

  String get craneFly3 => _currentMessages.generateStringAtIndex(104, []);

  String get craneFly3SemanticLabel =>
      _currentMessages.generateStringAtIndex(105, []);

  String get craneFly4 => _currentMessages.generateStringAtIndex(106, []);

  String get craneFly4SemanticLabel =>
      _currentMessages.generateStringAtIndex(107, []);

  String get craneFly5 => _currentMessages.generateStringAtIndex(108, []);

  String get craneFly5SemanticLabel =>
      _currentMessages.generateStringAtIndex(109, []);

  String get craneFly6 => _currentMessages.generateStringAtIndex(110, []);

  String get craneFly6SemanticLabel =>
      _currentMessages.generateStringAtIndex(111, []);

  String get craneFly7 => _currentMessages.generateStringAtIndex(112, []);

  String get craneFly7SemanticLabel =>
      _currentMessages.generateStringAtIndex(113, []);

  String get craneFly8 => _currentMessages.generateStringAtIndex(114, []);

  String get craneFly8SemanticLabel =>
      _currentMessages.generateStringAtIndex(115, []);

  String get craneFly9 => _currentMessages.generateStringAtIndex(116, []);

  String get craneFly9SemanticLabel =>
      _currentMessages.generateStringAtIndex(117, []);

  String craneFlyStops(int numberOfStops) =>
      _currentMessages.generateStringAtIndex(118, [numberOfStops]);

  String get craneFlySubhead => _currentMessages.generateStringAtIndex(119, []);

  String get craneFormDate => _currentMessages.generateStringAtIndex(120, []);

  String get craneFormDates => _currentMessages.generateStringAtIndex(121, []);

  String get craneFormDestination =>
      _currentMessages.generateStringAtIndex(122, []);

  String get craneFormDiners => _currentMessages.generateStringAtIndex(123, []);

  String get craneFormLocation =>
      _currentMessages.generateStringAtIndex(124, []);

  String get craneFormOrigin => _currentMessages.generateStringAtIndex(125, []);

  String get craneFormTime => _currentMessages.generateStringAtIndex(126, []);

  String get craneFormTravelers =>
      _currentMessages.generateStringAtIndex(127, []);

  String craneHours(int hours) =>
      _currentMessages.generateStringAtIndex(128, [hours]);

  String craneMinutes(int minutes) =>
      _currentMessages.generateStringAtIndex(129, [minutes]);

  String get craneSleep => _currentMessages.generateStringAtIndex(130, []);

  String get craneSleep0 => _currentMessages.generateStringAtIndex(131, []);

  String get craneSleep0SemanticLabel =>
      _currentMessages.generateStringAtIndex(132, []);

  String get craneSleep1 => _currentMessages.generateStringAtIndex(133, []);

  String get craneSleep10 => _currentMessages.generateStringAtIndex(134, []);

  String get craneSleep10SemanticLabel =>
      _currentMessages.generateStringAtIndex(135, []);

  String get craneSleep11 => _currentMessages.generateStringAtIndex(136, []);

  String get craneSleep11SemanticLabel =>
      _currentMessages.generateStringAtIndex(137, []);

  String get craneSleep1SemanticLabel =>
      _currentMessages.generateStringAtIndex(138, []);

  String get craneSleep2 => _currentMessages.generateStringAtIndex(139, []);

  String get craneSleep2SemanticLabel =>
      _currentMessages.generateStringAtIndex(140, []);

  String get craneSleep3 => _currentMessages.generateStringAtIndex(141, []);

  String get craneSleep3SemanticLabel =>
      _currentMessages.generateStringAtIndex(142, []);

  String get craneSleep4 => _currentMessages.generateStringAtIndex(143, []);

  String get craneSleep4SemanticLabel =>
      _currentMessages.generateStringAtIndex(144, []);

  String get craneSleep5 => _currentMessages.generateStringAtIndex(145, []);

  String get craneSleep5SemanticLabel =>
      _currentMessages.generateStringAtIndex(146, []);

  String get craneSleep6 => _currentMessages.generateStringAtIndex(147, []);

  String get craneSleep6SemanticLabel =>
      _currentMessages.generateStringAtIndex(148, []);

  String get craneSleep7 => _currentMessages.generateStringAtIndex(149, []);

  String get craneSleep7SemanticLabel =>
      _currentMessages.generateStringAtIndex(150, []);

  String get craneSleep8 => _currentMessages.generateStringAtIndex(151, []);

  String get craneSleep8SemanticLabel =>
      _currentMessages.generateStringAtIndex(152, []);

  String get craneSleep9 => _currentMessages.generateStringAtIndex(153, []);

  String get craneSleep9SemanticLabel =>
      _currentMessages.generateStringAtIndex(154, []);

  String craneSleepProperties(int totalProperties) =>
      _currentMessages.generateStringAtIndex(155, [totalProperties]);

  String get craneSleepSubhead =>
      _currentMessages.generateStringAtIndex(156, []);

  String get cupertinoAlertAllow =>
      _currentMessages.generateStringAtIndex(157, []);

  String get cupertinoAlertApplePie =>
      _currentMessages.generateStringAtIndex(158, []);

  String get cupertinoAlertCancel =>
      _currentMessages.generateStringAtIndex(159, []);

  String get cupertinoAlertCheesecake =>
      _currentMessages.generateStringAtIndex(160, []);

  String get cupertinoAlertChocolateBrownie =>
      _currentMessages.generateStringAtIndex(161, []);

  String get cupertinoAlertDessertDescription =>
      _currentMessages.generateStringAtIndex(162, []);

  String get cupertinoAlertDiscard =>
      _currentMessages.generateStringAtIndex(163, []);

  String get cupertinoAlertDontAllow =>
      _currentMessages.generateStringAtIndex(164, []);

  String get cupertinoAlertFavoriteDessert =>
      _currentMessages.generateStringAtIndex(165, []);

  String get cupertinoAlertLocationDescription =>
      _currentMessages.generateStringAtIndex(166, []);

  String get cupertinoAlertLocationTitle =>
      _currentMessages.generateStringAtIndex(167, []);

  String get cupertinoAlertTiramisu =>
      _currentMessages.generateStringAtIndex(168, []);

  String get cupertinoButton => _currentMessages.generateStringAtIndex(169, []);

  String get cupertinoButtonWithBackground =>
      _currentMessages.generateStringAtIndex(170, []);

  String get cupertinoShowAlert =>
      _currentMessages.generateStringAtIndex(171, []);

  String get cupertinoTabBarChatTab =>
      _currentMessages.generateStringAtIndex(172, []);

  String get cupertinoTabBarHomeTab =>
      _currentMessages.generateStringAtIndex(173, []);

  String get cupertinoTabBarProfileTab =>
      _currentMessages.generateStringAtIndex(174, []);

  String get dataTableColumnCalcium =>
      _currentMessages.generateStringAtIndex(175, []);

  String get dataTableColumnCalories =>
      _currentMessages.generateStringAtIndex(176, []);

  String get dataTableColumnCarbs =>
      _currentMessages.generateStringAtIndex(177, []);

  String get dataTableColumnDessert =>
      _currentMessages.generateStringAtIndex(178, []);

  String get dataTableColumnFat =>
      _currentMessages.generateStringAtIndex(179, []);

  String get dataTableColumnIron =>
      _currentMessages.generateStringAtIndex(180, []);

  String get dataTableColumnProtein =>
      _currentMessages.generateStringAtIndex(181, []);

  String get dataTableColumnSodium =>
      _currentMessages.generateStringAtIndex(182, []);

  String get dataTableHeader => _currentMessages.generateStringAtIndex(183, []);

  String get dataTableRowApplePie =>
      _currentMessages.generateStringAtIndex(184, []);

  String get dataTableRowCupcake =>
      _currentMessages.generateStringAtIndex(185, []);

  String get dataTableRowDonut =>
      _currentMessages.generateStringAtIndex(186, []);

  String get dataTableRowEclair =>
      _currentMessages.generateStringAtIndex(187, []);

  String get dataTableRowFrozenYogurt =>
      _currentMessages.generateStringAtIndex(188, []);

  String get dataTableRowGingerbread =>
      _currentMessages.generateStringAtIndex(189, []);

  String get dataTableRowHoneycomb =>
      _currentMessages.generateStringAtIndex(190, []);

  String get dataTableRowIceCreamSandwich =>
      _currentMessages.generateStringAtIndex(191, []);

  String get dataTableRowJellyBean =>
      _currentMessages.generateStringAtIndex(192, []);

  String get dataTableRowLollipop =>
      _currentMessages.generateStringAtIndex(193, []);

  String dataTableRowWithHoney(String value) =>
      _currentMessages.generateStringAtIndex(194, [value]);

  String dataTableRowWithSugar(String value) =>
      _currentMessages.generateStringAtIndex(195, [value]);

  String get demo => _currentMessages.generateStringAtIndex(196, []);

  String get demo2dTransformationsDescription =>
      _currentMessages.generateStringAtIndex(197, []);

  String get demo2dTransformationsEditTooltip =>
      _currentMessages.generateStringAtIndex(198, []);

  String get demo2dTransformationsResetTooltip =>
      _currentMessages.generateStringAtIndex(199, []);

  String get demo2dTransformationsSubtitle =>
      _currentMessages.generateStringAtIndex(200, []);

  String get demo2dTransformationsTitle =>
      _currentMessages.generateStringAtIndex(201, []);

  String get demoActionChipDescription =>
      _currentMessages.generateStringAtIndex(202, []);

  String get demoActionChipTitle =>
      _currentMessages.generateStringAtIndex(203, []);

  String get demoAlertDialogDescription =>
      _currentMessages.generateStringAtIndex(204, []);

  String get demoAlertDialogTitle =>
      _currentMessages.generateStringAtIndex(205, []);

  String get demoAlertTitleDialogTitle =>
      _currentMessages.generateStringAtIndex(206, []);

  String get demoAppBarDescription =>
      _currentMessages.generateStringAtIndex(207, []);

  String get demoAppBarSubtitle =>
      _currentMessages.generateStringAtIndex(208, []);

  String get demoAppBarTitle => _currentMessages.generateStringAtIndex(209, []);

  String get demoBannerDescription =>
      _currentMessages.generateStringAtIndex(210, []);

  String get demoBannerSubtitle =>
      _currentMessages.generateStringAtIndex(211, []);

  String get demoBannerTitle => _currentMessages.generateStringAtIndex(212, []);

  String get demoBottomAppBarDescription =>
      _currentMessages.generateStringAtIndex(213, []);

  String get demoBottomAppBarSubtitle =>
      _currentMessages.generateStringAtIndex(214, []);

  String get demoBottomAppBarTitle =>
      _currentMessages.generateStringAtIndex(215, []);

  String get demoBottomNavigationDescription =>
      _currentMessages.generateStringAtIndex(216, []);

  String get demoBottomNavigationPersistentLabels =>
      _currentMessages.generateStringAtIndex(217, []);

  String get demoBottomNavigationSelectedLabel =>
      _currentMessages.generateStringAtIndex(218, []);

  String get demoBottomNavigationSubtitle =>
      _currentMessages.generateStringAtIndex(219, []);

  String get demoBottomNavigationTitle =>
      _currentMessages.generateStringAtIndex(220, []);

  String get demoBottomSheetAddLabel =>
      _currentMessages.generateStringAtIndex(221, []);

  String get demoBottomSheetButtonText =>
      _currentMessages.generateStringAtIndex(222, []);

  String get demoBottomSheetHeader =>
      _currentMessages.generateStringAtIndex(223, []);

  String demoBottomSheetItem(int value) =>
      _currentMessages.generateStringAtIndex(224, [value]);

  String get demoBottomSheetModalDescription =>
      _currentMessages.generateStringAtIndex(225, []);

  String get demoBottomSheetModalTitle =>
      _currentMessages.generateStringAtIndex(226, []);

  String get demoBottomSheetPersistentDescription =>
      _currentMessages.generateStringAtIndex(227, []);

  String get demoBottomSheetPersistentTitle =>
      _currentMessages.generateStringAtIndex(228, []);

  String get demoBottomSheetSubtitle =>
      _currentMessages.generateStringAtIndex(229, []);

  String get demoBottomSheetTitle =>
      _currentMessages.generateStringAtIndex(230, []);

  String get demoBottomTextFieldsTitle =>
      _currentMessages.generateStringAtIndex(231, []);

  String get demoButtonSubtitle =>
      _currentMessages.generateStringAtIndex(232, []);

  String get demoButtonTitle => _currentMessages.generateStringAtIndex(233, []);

  String get demoCardDescription =>
      _currentMessages.generateStringAtIndex(234, []);

  String get demoCardSubtitle =>
      _currentMessages.generateStringAtIndex(235, []);

  String get demoCardTitle => _currentMessages.generateStringAtIndex(236, []);

  String get demoChecklistMenuTitle =>
      _currentMessages.generateStringAtIndex(237, []);

  String get demoChipSubtitle =>
      _currentMessages.generateStringAtIndex(238, []);

  String get demoChipTitle => _currentMessages.generateStringAtIndex(239, []);

  String get demoChoiceChipDescription =>
      _currentMessages.generateStringAtIndex(240, []);

  String get demoChoiceChipTitle =>
      _currentMessages.generateStringAtIndex(241, []);

  String get demoCircularProgressIndicatorDescription =>
      _currentMessages.generateStringAtIndex(242, []);

  String get demoCircularProgressIndicatorTitle =>
      _currentMessages.generateStringAtIndex(243, []);

  String get demoCodeTooltip => _currentMessages.generateStringAtIndex(244, []);

  String get demoCodeViewerCopiedToClipboardMessage =>
      _currentMessages.generateStringAtIndex(245, []);

  String get demoCodeViewerCopyAll =>
      _currentMessages.generateStringAtIndex(246, []);

  String demoCodeViewerFailedToCopyToClipboardMessage(Object error) =>
      _currentMessages.generateStringAtIndex(247, [error]);

  String get demoColorsDescription =>
      _currentMessages.generateStringAtIndex(248, []);

  String get demoColorsSubtitle =>
      _currentMessages.generateStringAtIndex(249, []);

  String get demoColorsTitle => _currentMessages.generateStringAtIndex(250, []);

  String get demoContainerTransformDemoInstructions =>
      _currentMessages.generateStringAtIndex(251, []);

  String get demoContainerTransformDescription =>
      _currentMessages.generateStringAtIndex(252, []);

  String get demoContainerTransformModalBottomSheetTitle =>
      _currentMessages.generateStringAtIndex(253, []);

  String get demoContainerTransformTitle =>
      _currentMessages.generateStringAtIndex(254, []);

  String get demoContainerTransformTypeFade =>
      _currentMessages.generateStringAtIndex(255, []);

  String get demoContainerTransformTypeFadeThrough =>
      _currentMessages.generateStringAtIndex(256, []);

  String get demoContextMenuTitle =>
      _currentMessages.generateStringAtIndex(257, []);

  String get demoCupertinoActionSheetDescription =>
      _currentMessages.generateStringAtIndex(258, []);

  String get demoCupertinoActionSheetTitle =>
      _currentMessages.generateStringAtIndex(259, []);

  String get demoCupertinoActivityIndicatorDescription =>
      _currentMessages.generateStringAtIndex(260, []);

  String get demoCupertinoActivityIndicatorSubtitle =>
      _currentMessages.generateStringAtIndex(261, []);

  String get demoCupertinoActivityIndicatorTitle =>
      _currentMessages.generateStringAtIndex(262, []);

  String get demoCupertinoAlertButtonsOnlyTitle =>
      _currentMessages.generateStringAtIndex(263, []);

  String get demoCupertinoAlertButtonsTitle =>
      _currentMessages.generateStringAtIndex(264, []);

  String get demoCupertinoAlertDescription =>
      _currentMessages.generateStringAtIndex(265, []);

  String get demoCupertinoAlertTitle =>
      _currentMessages.generateStringAtIndex(266, []);

  String get demoCupertinoAlertWithTitleTitle =>
      _currentMessages.generateStringAtIndex(267, []);

  String get demoCupertinoAlertsSubtitle =>
      _currentMessages.generateStringAtIndex(268, []);

  String get demoCupertinoAlertsTitle =>
      _currentMessages.generateStringAtIndex(269, []);

  String get demoCupertinoButtonsDescription =>
      _currentMessages.generateStringAtIndex(270, []);

  String get demoCupertinoButtonsSubtitle =>
      _currentMessages.generateStringAtIndex(271, []);

  String get demoCupertinoButtonsTitle =>
      _currentMessages.generateStringAtIndex(272, []);

  String get demoCupertinoContextMenuActionOne =>
      _currentMessages.generateStringAtIndex(273, []);

  String get demoCupertinoContextMenuActionText =>
      _currentMessages.generateStringAtIndex(274, []);

  String get demoCupertinoContextMenuActionTwo =>
      _currentMessages.generateStringAtIndex(275, []);

  String get demoCupertinoContextMenuDescription =>
      _currentMessages.generateStringAtIndex(276, []);

  String get demoCupertinoContextMenuSubtitle =>
      _currentMessages.generateStringAtIndex(277, []);

  String get demoCupertinoContextMenuTitle =>
      _currentMessages.generateStringAtIndex(278, []);

  String get demoCupertinoNavigationBarDescription =>
      _currentMessages.generateStringAtIndex(279, []);

  String get demoCupertinoNavigationBarSubtitle =>
      _currentMessages.generateStringAtIndex(280, []);

  String get demoCupertinoNavigationBarTitle =>
      _currentMessages.generateStringAtIndex(281, []);

  String get demoCupertinoPicker =>
      _currentMessages.generateStringAtIndex(282, []);

  String get demoCupertinoPickerDate =>
      _currentMessages.generateStringAtIndex(283, []);

  String get demoCupertinoPickerDateTime =>
      _currentMessages.generateStringAtIndex(284, []);

  String get demoCupertinoPickerDescription =>
      _currentMessages.generateStringAtIndex(285, []);

  String get demoCupertinoPickerSubtitle =>
      _currentMessages.generateStringAtIndex(286, []);

  String get demoCupertinoPickerTime =>
      _currentMessages.generateStringAtIndex(287, []);

  String get demoCupertinoPickerTimer =>
      _currentMessages.generateStringAtIndex(288, []);

  String get demoCupertinoPickerTitle =>
      _currentMessages.generateStringAtIndex(289, []);

  String get demoCupertinoPullToRefreshDescription =>
      _currentMessages.generateStringAtIndex(290, []);

  String get demoCupertinoPullToRefreshSubtitle =>
      _currentMessages.generateStringAtIndex(291, []);

  String get demoCupertinoPullToRefreshTitle =>
      _currentMessages.generateStringAtIndex(292, []);

  String get demoCupertinoScrollbarDescription =>
      _currentMessages.generateStringAtIndex(293, []);

  String get demoCupertinoScrollbarSubtitle =>
      _currentMessages.generateStringAtIndex(294, []);

  String get demoCupertinoScrollbarTitle =>
      _currentMessages.generateStringAtIndex(295, []);

  String get demoCupertinoSearchTextFieldDescription =>
      _currentMessages.generateStringAtIndex(296, []);

  String get demoCupertinoSearchTextFieldPlaceholder =>
      _currentMessages.generateStringAtIndex(297, []);

  String get demoCupertinoSearchTextFieldSubtitle =>
      _currentMessages.generateStringAtIndex(298, []);

  String get demoCupertinoSearchTextFieldTitle =>
      _currentMessages.generateStringAtIndex(299, []);

  String get demoCupertinoSegmentedControlDescription =>
      _currentMessages.generateStringAtIndex(300, []);

  String get demoCupertinoSegmentedControlSubtitle =>
      _currentMessages.generateStringAtIndex(301, []);

  String get demoCupertinoSegmentedControlTitle =>
      _currentMessages.generateStringAtIndex(302, []);

  String demoCupertinoSliderContinuous(String value) =>
      _currentMessages.generateStringAtIndex(303, [value]);

  String get demoCupertinoSliderDescription =>
      _currentMessages.generateStringAtIndex(304, []);

  String demoCupertinoSliderDiscrete(String value) =>
      _currentMessages.generateStringAtIndex(305, [value]);

  String get demoCupertinoSliderSubtitle =>
      _currentMessages.generateStringAtIndex(306, []);

  String get demoCupertinoSliderTitle =>
      _currentMessages.generateStringAtIndex(307, []);

  String get demoCupertinoSwitchDescription =>
      _currentMessages.generateStringAtIndex(308, []);

  String get demoCupertinoSwitchSubtitle =>
      _currentMessages.generateStringAtIndex(309, []);

  String get demoCupertinoTabBarDescription =>
      _currentMessages.generateStringAtIndex(310, []);

  String get demoCupertinoTabBarSubtitle =>
      _currentMessages.generateStringAtIndex(311, []);

  String get demoCupertinoTabBarTitle =>
      _currentMessages.generateStringAtIndex(312, []);

  String get demoCupertinoTextFieldDescription =>
      _currentMessages.generateStringAtIndex(313, []);

  String get demoCupertinoTextFieldPIN =>
      _currentMessages.generateStringAtIndex(314, []);

  String get demoCupertinoTextFieldSubtitle =>
      _currentMessages.generateStringAtIndex(315, []);

  String get demoCupertinoTextFieldTitle =>
      _currentMessages.generateStringAtIndex(316, []);

  String get demoCustomSlidersDescription =>
      _currentMessages.generateStringAtIndex(317, []);

  String get demoCustomSlidersTitle =>
      _currentMessages.generateStringAtIndex(318, []);

  String get demoDataTableDescription =>
      _currentMessages.generateStringAtIndex(319, []);

  String get demoDataTableSubtitle =>
      _currentMessages.generateStringAtIndex(320, []);

  String get demoDataTableTitle =>
      _currentMessages.generateStringAtIndex(321, []);

  String get demoDatePickerDescription =>
      _currentMessages.generateStringAtIndex(322, []);

  String get demoDatePickerTitle =>
      _currentMessages.generateStringAtIndex(323, []);

  String get demoDateRangePickerDescription =>
      _currentMessages.generateStringAtIndex(324, []);

  String get demoDateRangePickerTitle =>
      _currentMessages.generateStringAtIndex(325, []);

  String get demoDialogSubtitle =>
      _currentMessages.generateStringAtIndex(326, []);

  String get demoDialogTitle => _currentMessages.generateStringAtIndex(327, []);

  String get demoDividerDescription =>
      _currentMessages.generateStringAtIndex(328, []);

  String get demoDividerSubtitle =>
      _currentMessages.generateStringAtIndex(329, []);

  String get demoDividerTitle =>
      _currentMessages.generateStringAtIndex(330, []);

  String get demoDocumentationTooltip =>
      _currentMessages.generateStringAtIndex(331, []);

  String get demoElevatedButtonDescription =>
      _currentMessages.generateStringAtIndex(332, []);

  String get demoElevatedButtonTitle =>
      _currentMessages.generateStringAtIndex(333, []);

  String get demoFadeScaleAlertDialogCancelButton =>
      _currentMessages.generateStringAtIndex(334, []);

  String get demoFadeScaleAlertDialogDiscardButton =>
      _currentMessages.generateStringAtIndex(335, []);

  String get demoFadeScaleAlertDialogHeader =>
      _currentMessages.generateStringAtIndex(336, []);

  String get demoFadeScaleDemoInstructions =>
      _currentMessages.generateStringAtIndex(337, []);

  String get demoFadeScaleDescription =>
      _currentMessages.generateStringAtIndex(338, []);

  String get demoFadeScaleHideFabButton =>
      _currentMessages.generateStringAtIndex(339, []);

  String get demoFadeScaleShowAlertDialogButton =>
      _currentMessages.generateStringAtIndex(340, []);

  String get demoFadeScaleShowFabButton =>
      _currentMessages.generateStringAtIndex(341, []);

  String get demoFadeScaleTitle =>
      _currentMessages.generateStringAtIndex(342, []);

  String get demoFadeThroughAlbumsDestination =>
      _currentMessages.generateStringAtIndex(343, []);

  String get demoFadeThroughDemoInstructions =>
      _currentMessages.generateStringAtIndex(344, []);

  String get demoFadeThroughDescription =>
      _currentMessages.generateStringAtIndex(345, []);

  String get demoFadeThroughPhotosDestination =>
      _currentMessages.generateStringAtIndex(346, []);

  String get demoFadeThroughSearchDestination =>
      _currentMessages.generateStringAtIndex(347, []);

  String get demoFadeThroughTextPlaceholder =>
      _currentMessages.generateStringAtIndex(348, []);

  String get demoFadeThroughTitle =>
      _currentMessages.generateStringAtIndex(349, []);

  String get demoFilterChipDescription =>
      _currentMessages.generateStringAtIndex(350, []);

  String get demoFilterChipTitle =>
      _currentMessages.generateStringAtIndex(351, []);

  String get demoFloatingButtonDescription =>
      _currentMessages.generateStringAtIndex(352, []);

  String get demoFloatingButtonTitle =>
      _currentMessages.generateStringAtIndex(353, []);

  String get demoFullscreenDialogDescription =>
      _currentMessages.generateStringAtIndex(354, []);

  String get demoFullscreenDialogTitle =>
      _currentMessages.generateStringAtIndex(355, []);

  String get demoFullscreenTooltip =>
      _currentMessages.generateStringAtIndex(356, []);

  String get demoGridListsDescription =>
      _currentMessages.generateStringAtIndex(357, []);

  String get demoGridListsFooterTitle =>
      _currentMessages.generateStringAtIndex(358, []);

  String get demoGridListsHeaderTitle =>
      _currentMessages.generateStringAtIndex(359, []);

  String get demoGridListsImageOnlyTitle =>
      _currentMessages.generateStringAtIndex(360, []);

  String get demoGridListsSubtitle =>
      _currentMessages.generateStringAtIndex(361, []);

  String get demoGridListsTitle =>
      _currentMessages.generateStringAtIndex(362, []);

  String get demoInfoTooltip => _currentMessages.generateStringAtIndex(363, []);

  String get demoInputChipDescription =>
      _currentMessages.generateStringAtIndex(364, []);

  String get demoInputChipTitle =>
      _currentMessages.generateStringAtIndex(365, []);

  String get demoInvalidURL => _currentMessages.generateStringAtIndex(366, []);

  String get demoLinearProgressIndicatorDescription =>
      _currentMessages.generateStringAtIndex(367, []);

  String get demoLinearProgressIndicatorTitle =>
      _currentMessages.generateStringAtIndex(368, []);

  String get demoListsDescription =>
      _currentMessages.generateStringAtIndex(369, []);

  String get demoListsSecondary =>
      _currentMessages.generateStringAtIndex(370, []);

  String get demoListsSubtitle =>
      _currentMessages.generateStringAtIndex(371, []);

  String get demoListsTitle => _currentMessages.generateStringAtIndex(372, []);

  String get demoMenuADisabledMenuItem =>
      _currentMessages.generateStringAtIndex(373, []);

  String get demoMenuAnItemWithAChecklistMenu =>
      _currentMessages.generateStringAtIndex(374, []);

  String get demoMenuAnItemWithAContextMenuButton =>
      _currentMessages.generateStringAtIndex(375, []);

  String get demoMenuAnItemWithASectionedMenu =>
      _currentMessages.generateStringAtIndex(376, []);

  String get demoMenuAnItemWithASimpleMenu =>
      _currentMessages.generateStringAtIndex(377, []);

  String demoMenuChecked(Iterable<String> value) =>
      _currentMessages.generateStringAtIndex(378, [value]);

  String get demoMenuContextMenuItemOne =>
      _currentMessages.generateStringAtIndex(379, []);

  String get demoMenuContextMenuItemThree =>
      _currentMessages.generateStringAtIndex(380, []);

  String get demoMenuDescription =>
      _currentMessages.generateStringAtIndex(381, []);

  String get demoMenuFour => _currentMessages.generateStringAtIndex(382, []);

  String get demoMenuGetLink => _currentMessages.generateStringAtIndex(383, []);

  String get demoMenuItemValueOne =>
      _currentMessages.generateStringAtIndex(384, []);

  String get demoMenuItemValueThree =>
      _currentMessages.generateStringAtIndex(385, []);

  String get demoMenuItemValueTwo =>
      _currentMessages.generateStringAtIndex(386, []);

  String get demoMenuOne => _currentMessages.generateStringAtIndex(387, []);

  String get demoMenuPreview => _currentMessages.generateStringAtIndex(388, []);

  String get demoMenuRemove => _currentMessages.generateStringAtIndex(389, []);

  String demoMenuSelected(String value) =>
      _currentMessages.generateStringAtIndex(390, [value]);

  String get demoMenuShare => _currentMessages.generateStringAtIndex(391, []);

  String get demoMenuSubtitle =>
      _currentMessages.generateStringAtIndex(392, []);

  String get demoMenuThree => _currentMessages.generateStringAtIndex(393, []);

  String get demoMenuTitle => _currentMessages.generateStringAtIndex(394, []);

  String get demoMenuTwo => _currentMessages.generateStringAtIndex(395, []);

  String get demoMotionDetailsPageTitle =>
      _currentMessages.generateStringAtIndex(396, []);

  String get demoMotionListTileTitle =>
      _currentMessages.generateStringAtIndex(397, []);

  String get demoMotionPlaceholderSubtitle =>
      _currentMessages.generateStringAtIndex(398, []);

  String get demoMotionPlaceholderTitle =>
      _currentMessages.generateStringAtIndex(399, []);

  String get demoMotionSmallPlaceholderSubtitle =>
      _currentMessages.generateStringAtIndex(400, []);

  String get demoMotionSubtitle =>
      _currentMessages.generateStringAtIndex(401, []);

  String get demoMotionTitle => _currentMessages.generateStringAtIndex(402, []);

  String get demoNavigationDrawerDescription =>
      _currentMessages.generateStringAtIndex(403, []);

  String get demoNavigationDrawerSubtitle =>
      _currentMessages.generateStringAtIndex(404, []);

  String get demoNavigationDrawerText =>
      _currentMessages.generateStringAtIndex(405, []);

  String get demoNavigationDrawerTitle =>
      _currentMessages.generateStringAtIndex(406, []);

  String get demoNavigationDrawerToPageOne =>
      _currentMessages.generateStringAtIndex(407, []);

  String get demoNavigationDrawerToPageTwo =>
      _currentMessages.generateStringAtIndex(408, []);

  String get demoNavigationDrawerUserEmail =>
      _currentMessages.generateStringAtIndex(409, []);

  String get demoNavigationDrawerUserName =>
      _currentMessages.generateStringAtIndex(410, []);

  String get demoNavigationRailDescription =>
      _currentMessages.generateStringAtIndex(411, []);

  String get demoNavigationRailFirst =>
      _currentMessages.generateStringAtIndex(412, []);

  String get demoNavigationRailSecond =>
      _currentMessages.generateStringAtIndex(413, []);

  String get demoNavigationRailSubtitle =>
      _currentMessages.generateStringAtIndex(414, []);

  String get demoNavigationRailThird =>
      _currentMessages.generateStringAtIndex(415, []);

  String get demoNavigationRailTitle =>
      _currentMessages.generateStringAtIndex(416, []);

  String get demoOneLineListsTitle =>
      _currentMessages.generateStringAtIndex(417, []);

  String get demoOptionsFeatureDescription =>
      _currentMessages.generateStringAtIndex(418, []);

  String get demoOptionsFeatureTitle =>
      _currentMessages.generateStringAtIndex(419, []);

  String get demoOptionsTooltip =>
      _currentMessages.generateStringAtIndex(420, []);

  String get demoOutlinedButtonDescription =>
      _currentMessages.generateStringAtIndex(421, []);

  String get demoOutlinedButtonTitle =>
      _currentMessages.generateStringAtIndex(422, []);

  String get demoPickersShowPicker =>
      _currentMessages.generateStringAtIndex(423, []);

  String get demoPickersSubtitle =>
      _currentMessages.generateStringAtIndex(424, []);

  String get demoPickersTitle =>
      _currentMessages.generateStringAtIndex(425, []);

  String get demoProgressIndicatorSubtitle =>
      _currentMessages.generateStringAtIndex(426, []);

  String get demoProgressIndicatorTitle =>
      _currentMessages.generateStringAtIndex(427, []);

  String get demoRangeSlidersDescription =>
      _currentMessages.generateStringAtIndex(428, []);

  String get demoRangeSlidersTitle =>
      _currentMessages.generateStringAtIndex(429, []);

  String get demoSectionedMenuTitle =>
      _currentMessages.generateStringAtIndex(430, []);

  String get demoSelectionControlsCheckboxDescription =>
      _currentMessages.generateStringAtIndex(431, []);

  String get demoSelectionControlsCheckboxTitle =>
      _currentMessages.generateStringAtIndex(432, []);

  String get demoSelectionControlsRadioDescription =>
      _currentMessages.generateStringAtIndex(433, []);

  String get demoSelectionControlsRadioTitle =>
      _currentMessages.generateStringAtIndex(434, []);

  String get demoSelectionControlsSubtitle =>
      _currentMessages.generateStringAtIndex(435, []);

  String get demoSelectionControlsSwitchDescription =>
      _currentMessages.generateStringAtIndex(436, []);

  String get demoSelectionControlsSwitchTitle =>
      _currentMessages.generateStringAtIndex(437, []);

  String get demoSelectionControlsTitle =>
      _currentMessages.generateStringAtIndex(438, []);

  String get demoSharedAxisDescription =>
      _currentMessages.generateStringAtIndex(439, []);

  String get demoSharedXAxisArtsAndCraftsCourseTitle =>
      _currentMessages.generateStringAtIndex(440, []);

  String get demoSharedXAxisBackButtonText =>
      _currentMessages.generateStringAtIndex(441, []);

  String get demoSharedXAxisBundledCourseSubtitle =>
      _currentMessages.generateStringAtIndex(442, []);

  String get demoSharedXAxisBusinessCourseTitle =>
      _currentMessages.generateStringAtIndex(443, []);

  String get demoSharedXAxisCoursePageSubtitle =>
      _currentMessages.generateStringAtIndex(444, []);

  String get demoSharedXAxisCoursePageTitle =>
      _currentMessages.generateStringAtIndex(445, []);

  String get demoSharedXAxisCreateAccountButtonText =>
      _currentMessages.generateStringAtIndex(446, []);

  String get demoSharedXAxisCulinaryCourseTitle =>
      _currentMessages.generateStringAtIndex(447, []);

  String get demoSharedXAxisDemoInstructions =>
      _currentMessages.generateStringAtIndex(448, []);

  String get demoSharedXAxisDesignCourseTitle =>
      _currentMessages.generateStringAtIndex(449, []);

  String get demoSharedXAxisForgotEmailButtonText =>
      _currentMessages.generateStringAtIndex(450, []);

  String get demoSharedXAxisIllustrationCourseTitle =>
      _currentMessages.generateStringAtIndex(451, []);

  String get demoSharedXAxisIndividualCourseSubtitle =>
      _currentMessages.generateStringAtIndex(452, []);

  String get demoSharedXAxisNextButtonText =>
      _currentMessages.generateStringAtIndex(453, []);

  String get demoSharedXAxisSignInSubtitleText =>
      _currentMessages.generateStringAtIndex(454, []);

  String get demoSharedXAxisSignInTextFieldLabel =>
      _currentMessages.generateStringAtIndex(455, []);

  String get demoSharedXAxisSignInWelcomeText =>
      _currentMessages.generateStringAtIndex(456, []);

  String get demoSharedXAxisTitle =>
      _currentMessages.generateStringAtIndex(457, []);

  String get demoSharedYAxisAlbumCount =>
      _currentMessages.generateStringAtIndex(458, []);

  String get demoSharedYAxisAlbumTileDurationUnit =>
      _currentMessages.generateStringAtIndex(459, []);

  String get demoSharedYAxisAlbumTileSubtitle =>
      _currentMessages.generateStringAtIndex(460, []);

  String get demoSharedYAxisAlbumTileTitle =>
      _currentMessages.generateStringAtIndex(461, []);

  String get demoSharedYAxisAlphabeticalSortTitle =>
      _currentMessages.generateStringAtIndex(462, []);

  String get demoSharedYAxisDemoInstructions =>
      _currentMessages.generateStringAtIndex(463, []);

  String get demoSharedYAxisRecentSortTitle =>
      _currentMessages.generateStringAtIndex(464, []);

  String get demoSharedYAxisTitle =>
      _currentMessages.generateStringAtIndex(465, []);

  String get demoSharedZAxisBeefSandwichRecipeDescription =>
      _currentMessages.generateStringAtIndex(466, []);

  String get demoSharedZAxisBeefSandwichRecipeTitle =>
      _currentMessages.generateStringAtIndex(467, []);

  String get demoSharedZAxisBurgerRecipeDescription =>
      _currentMessages.generateStringAtIndex(468, []);

  String get demoSharedZAxisBurgerRecipeTitle =>
      _currentMessages.generateStringAtIndex(469, []);

  String get demoSharedZAxisCrabPlateRecipeDescription =>
      _currentMessages.generateStringAtIndex(470, []);

  String get demoSharedZAxisCrabPlateRecipeTitle =>
      _currentMessages.generateStringAtIndex(471, []);

  String get demoSharedZAxisDemoInstructions =>
      _currentMessages.generateStringAtIndex(472, []);

  String get demoSharedZAxisDessertRecipeDescription =>
      _currentMessages.generateStringAtIndex(473, []);

  String get demoSharedZAxisDessertRecipeTitle =>
      _currentMessages.generateStringAtIndex(474, []);

  String get demoSharedZAxisHelpSettingLabel =>
      _currentMessages.generateStringAtIndex(475, []);

  String get demoSharedZAxisNotificationSettingLabel =>
      _currentMessages.generateStringAtIndex(476, []);

  String get demoSharedZAxisPrivacySettingLabel =>
      _currentMessages.generateStringAtIndex(477, []);

  String get demoSharedZAxisProfileSettingLabel =>
      _currentMessages.generateStringAtIndex(478, []);

  String get demoSharedZAxisSandwichRecipeDescription =>
      _currentMessages.generateStringAtIndex(479, []);

  String get demoSharedZAxisSandwichRecipeTitle =>
      _currentMessages.generateStringAtIndex(480, []);

  String get demoSharedZAxisSavedRecipesListTitle =>
      _currentMessages.generateStringAtIndex(481, []);

  String get demoSharedZAxisSettingsPageTitle =>
      _currentMessages.generateStringAtIndex(482, []);

  String get demoSharedZAxisShrimpPlateRecipeDescription =>
      _currentMessages.generateStringAtIndex(483, []);

  String get demoSharedZAxisShrimpPlateRecipeTitle =>
      _currentMessages.generateStringAtIndex(484, []);

  String get demoSharedZAxisTitle =>
      _currentMessages.generateStringAtIndex(485, []);

  String get demoSimpleDialogDescription =>
      _currentMessages.generateStringAtIndex(486, []);

  String get demoSimpleDialogTitle =>
      _currentMessages.generateStringAtIndex(487, []);

  String get demoSimpleMenuTitle =>
      _currentMessages.generateStringAtIndex(488, []);

  String get demoSlidersContinuous =>
      _currentMessages.generateStringAtIndex(489, []);

  String get demoSlidersContinuousRangeSliderWithCustomTheme =>
      _currentMessages.generateStringAtIndex(490, []);

  String get demoSlidersContinuousWithEditableNumericalValue =>
      _currentMessages.generateStringAtIndex(491, []);

  String get demoSlidersDescription =>
      _currentMessages.generateStringAtIndex(492, []);

  String get demoSlidersDiscrete =>
      _currentMessages.generateStringAtIndex(493, []);

  String get demoSlidersDiscreteSliderWithCustomTheme =>
      _currentMessages.generateStringAtIndex(494, []);

  String get demoSlidersEditableNumericalValue =>
      _currentMessages.generateStringAtIndex(495, []);

  String get demoSlidersSubtitle =>
      _currentMessages.generateStringAtIndex(496, []);

  String get demoSlidersTitle =>
      _currentMessages.generateStringAtIndex(497, []);

  String get demoSnackbarsAction =>
      _currentMessages.generateStringAtIndex(498, []);

  String get demoSnackbarsActionButtonLabel =>
      _currentMessages.generateStringAtIndex(499, []);

  String get demoSnackbarsButtonLabel =>
      _currentMessages.generateStringAtIndex(500, []);

  String get demoSnackbarsDescription =>
      _currentMessages.generateStringAtIndex(501, []);

  String get demoSnackbarsSubtitle =>
      _currentMessages.generateStringAtIndex(502, []);

  String get demoSnackbarsText =>
      _currentMessages.generateStringAtIndex(503, []);

  String get demoSnackbarsTitle =>
      _currentMessages.generateStringAtIndex(504, []);

  String get demoTabsDescription =>
      _currentMessages.generateStringAtIndex(505, []);

  String get demoTabsNonScrollingTitle =>
      _currentMessages.generateStringAtIndex(506, []);

  String get demoTabsScrollingTitle =>
      _currentMessages.generateStringAtIndex(507, []);

  String get demoTabsSubtitle =>
      _currentMessages.generateStringAtIndex(508, []);

  String get demoTabsTitle => _currentMessages.generateStringAtIndex(509, []);

  String get demoTextButtonDescription =>
      _currentMessages.generateStringAtIndex(510, []);

  String get demoTextButtonTitle =>
      _currentMessages.generateStringAtIndex(511, []);

  String get demoTextFieldDescription =>
      _currentMessages.generateStringAtIndex(512, []);

  String get demoTextFieldEmail =>
      _currentMessages.generateStringAtIndex(513, []);

  String get demoTextFieldEnterPassword =>
      _currentMessages.generateStringAtIndex(514, []);

  String get demoTextFieldEnterUSPhoneNumber =>
      _currentMessages.generateStringAtIndex(515, []);

  String get demoTextFieldFormErrors =>
      _currentMessages.generateStringAtIndex(516, []);

  String get demoTextFieldHidePasswordLabel =>
      _currentMessages.generateStringAtIndex(517, []);

  String get demoTextFieldKeepItShort =>
      _currentMessages.generateStringAtIndex(518, []);

  String get demoTextFieldLifeStory =>
      _currentMessages.generateStringAtIndex(519, []);

  String get demoTextFieldNameField =>
      _currentMessages.generateStringAtIndex(520, []);

  String demoTextFieldNameHasPhoneNumber(
    String name,
    String phoneNumber,
  ) =>
      _currentMessages.generateStringAtIndex(521, [name, phoneNumber]);

  String get demoTextFieldNameRequired =>
      _currentMessages.generateStringAtIndex(522, []);

  String get demoTextFieldNoMoreThan =>
      _currentMessages.generateStringAtIndex(523, []);

  String get demoTextFieldOnlyAlphabeticalChars =>
      _currentMessages.generateStringAtIndex(524, []);

  String get demoTextFieldPassword =>
      _currentMessages.generateStringAtIndex(525, []);

  String get demoTextFieldPasswordsDoNotMatch =>
      _currentMessages.generateStringAtIndex(526, []);

  String get demoTextFieldPhoneNumber =>
      _currentMessages.generateStringAtIndex(527, []);

  String get demoTextFieldRequiredField =>
      _currentMessages.generateStringAtIndex(528, []);

  String get demoTextFieldRetypePassword =>
      _currentMessages.generateStringAtIndex(529, []);

  String get demoTextFieldSalary =>
      _currentMessages.generateStringAtIndex(530, []);

  String get demoTextFieldShowPasswordLabel =>
      _currentMessages.generateStringAtIndex(531, []);

  String get demoTextFieldSubmit =>
      _currentMessages.generateStringAtIndex(532, []);

  String get demoTextFieldSubtitle =>
      _currentMessages.generateStringAtIndex(533, []);

  String get demoTextFieldTellUsAboutYourself =>
      _currentMessages.generateStringAtIndex(534, []);

  String get demoTextFieldTitle =>
      _currentMessages.generateStringAtIndex(535, []);

  String get demoTextFieldUSD =>
      _currentMessages.generateStringAtIndex(536, []);

  String get demoTextFieldWhatDoPeopleCallYou =>
      _currentMessages.generateStringAtIndex(537, []);

  String get demoTextFieldWhereCanWeReachYou =>
      _currentMessages.generateStringAtIndex(538, []);

  String get demoTextFieldYourEmailAddress =>
      _currentMessages.generateStringAtIndex(539, []);

  String get demoTimePickerDescription =>
      _currentMessages.generateStringAtIndex(540, []);

  String get demoTimePickerTitle =>
      _currentMessages.generateStringAtIndex(541, []);

  String get demoToggleButtonDescription =>
      _currentMessages.generateStringAtIndex(542, []);

  String get demoToggleButtonTitle =>
      _currentMessages.generateStringAtIndex(543, []);

  String get demoTooltipDescription =>
      _currentMessages.generateStringAtIndex(544, []);

  String get demoTooltipInstructions =>
      _currentMessages.generateStringAtIndex(545, []);

  String get demoTooltipSubtitle =>
      _currentMessages.generateStringAtIndex(546, []);

  String get demoTooltipTitle =>
      _currentMessages.generateStringAtIndex(547, []);

  String get demoTwoLineListsTitle =>
      _currentMessages.generateStringAtIndex(548, []);

  String get demoTwoPaneDetails =>
      _currentMessages.generateStringAtIndex(549, []);

  String get demoTwoPaneFoldableDescription =>
      _currentMessages.generateStringAtIndex(550, []);

  String get demoTwoPaneFoldableLabel =>
      _currentMessages.generateStringAtIndex(551, []);

  String demoTwoPaneItem(int value) =>
      _currentMessages.generateStringAtIndex(552, [value]);

  String demoTwoPaneItemDetails(int value) =>
      _currentMessages.generateStringAtIndex(553, [value]);

  String get demoTwoPaneList => _currentMessages.generateStringAtIndex(554, []);

  String get demoTwoPaneSelectItem =>
      _currentMessages.generateStringAtIndex(555, []);

  String get demoTwoPaneSmallScreenDescription =>
      _currentMessages.generateStringAtIndex(556, []);

  String get demoTwoPaneSmallScreenLabel =>
      _currentMessages.generateStringAtIndex(557, []);

  String get demoTwoPaneSubtitle =>
      _currentMessages.generateStringAtIndex(558, []);

  String get demoTwoPaneTabletDescription =>
      _currentMessages.generateStringAtIndex(559, []);

  String get demoTwoPaneTabletLabel =>
      _currentMessages.generateStringAtIndex(560, []);

  String get demoTwoPaneTitle =>
      _currentMessages.generateStringAtIndex(561, []);

  String get demoTypographyDescription =>
      _currentMessages.generateStringAtIndex(562, []);

  String get demoTypographySubtitle =>
      _currentMessages.generateStringAtIndex(563, []);

  String get demoTypographyTitle =>
      _currentMessages.generateStringAtIndex(564, []);

  String get demoVerticalDividerTitle =>
      _currentMessages.generateStringAtIndex(565, []);

  String get deselect => _currentMessages.generateStringAtIndex(566, []);

  String get dialogAddAccount =>
      _currentMessages.generateStringAtIndex(567, []);

  String get dialogAgree => _currentMessages.generateStringAtIndex(568, []);

  String get dialogCancel => _currentMessages.generateStringAtIndex(569, []);

  String get dialogDisagree => _currentMessages.generateStringAtIndex(570, []);

  String get dialogDiscard => _currentMessages.generateStringAtIndex(571, []);

  String get dialogDiscardTitle =>
      _currentMessages.generateStringAtIndex(572, []);

  String get dialogFullscreenDescription =>
      _currentMessages.generateStringAtIndex(573, []);

  String get dialogFullscreenSave =>
      _currentMessages.generateStringAtIndex(574, []);

  String get dialogFullscreenTitle =>
      _currentMessages.generateStringAtIndex(575, []);

  String get dialogLocationDescription =>
      _currentMessages.generateStringAtIndex(576, []);

  String get dialogLocationTitle =>
      _currentMessages.generateStringAtIndex(577, []);

  String dialogSelectedOption(String value) =>
      _currentMessages.generateStringAtIndex(578, [value]);

  String get dialogSetBackup => _currentMessages.generateStringAtIndex(579, []);

  String get dialogShow => _currentMessages.generateStringAtIndex(580, []);

  String get dismiss => _currentMessages.generateStringAtIndex(581, []);

  String get fortnightlyDescription =>
      _currentMessages.generateStringAtIndex(582, []);

  String get fortnightlyHeadlineArmy =>
      _currentMessages.generateStringAtIndex(583, []);

  String get fortnightlyHeadlineBees =>
      _currentMessages.generateStringAtIndex(584, []);

  String get fortnightlyHeadlineFabrics =>
      _currentMessages.generateStringAtIndex(585, []);

  String get fortnightlyHeadlineFeminists =>
      _currentMessages.generateStringAtIndex(586, []);

  String get fortnightlyHeadlineGasoline =>
      _currentMessages.generateStringAtIndex(587, []);

  String get fortnightlyHeadlineHealthcare =>
      _currentMessages.generateStringAtIndex(588, []);

  String get fortnightlyHeadlineStocks =>
      _currentMessages.generateStringAtIndex(589, []);

  String get fortnightlyHeadlineWar =>
      _currentMessages.generateStringAtIndex(590, []);

  String get fortnightlyLatestUpdates =>
      _currentMessages.generateStringAtIndex(591, []);

  String get fortnightlyMenuBusiness =>
      _currentMessages.generateStringAtIndex(592, []);

  String get fortnightlyMenuCulture =>
      _currentMessages.generateStringAtIndex(593, []);

  String get fortnightlyMenuFrontPage =>
      _currentMessages.generateStringAtIndex(594, []);

  String get fortnightlyMenuPolitics =>
      _currentMessages.generateStringAtIndex(595, []);

  String get fortnightlyMenuScience =>
      _currentMessages.generateStringAtIndex(596, []);

  String get fortnightlyMenuSports =>
      _currentMessages.generateStringAtIndex(597, []);

  String get fortnightlyMenuTech =>
      _currentMessages.generateStringAtIndex(598, []);

  String get fortnightlyMenuTravel =>
      _currentMessages.generateStringAtIndex(599, []);

  String get fortnightlyMenuUS =>
      _currentMessages.generateStringAtIndex(600, []);

  String get fortnightlyMenuWorld =>
      _currentMessages.generateStringAtIndex(601, []);

  String get fortnightlyTrendingGreenArmy =>
      _currentMessages.generateStringAtIndex(602, []);

  String get fortnightlyTrendingHealthcareRevolution =>
      _currentMessages.generateStringAtIndex(603, []);

  String get fortnightlyTrendingReform =>
      _currentMessages.generateStringAtIndex(604, []);

  String get fortnightlyTrendingStocks =>
      _currentMessages.generateStringAtIndex(605, []);

  String get fortnightlyTrendingTechDesign =>
      _currentMessages.generateStringAtIndex(606, []);

  String githubRepo(String repoName) =>
      _currentMessages.generateStringAtIndex(607, [repoName]);

  String get homeCategoryReference =>
      _currentMessages.generateStringAtIndex(608, []);

  String get homeHeaderCategories =>
      _currentMessages.generateStringAtIndex(609, []);

  String get homeHeaderGallery =>
      _currentMessages.generateStringAtIndex(610, []);

  String get loading => _currentMessages.generateStringAtIndex(611, []);

  String get notSelected => _currentMessages.generateStringAtIndex(612, []);

  String get placeBeach => _currentMessages.generateStringAtIndex(613, []);

  String get placeBronzeWorks =>
      _currentMessages.generateStringAtIndex(614, []);

  String get placeChennai => _currentMessages.generateStringAtIndex(615, []);

  String get placeChettinad => _currentMessages.generateStringAtIndex(616, []);

  String get placeFisherman => _currentMessages.generateStringAtIndex(617, []);

  String get placeFlowerMarket =>
      _currentMessages.generateStringAtIndex(618, []);

  String get placeLunchPrep => _currentMessages.generateStringAtIndex(619, []);

  String get placeMarket => _currentMessages.generateStringAtIndex(620, []);

  String get placePondicherry =>
      _currentMessages.generateStringAtIndex(621, []);

  String get placeSaltFarm => _currentMessages.generateStringAtIndex(622, []);

  String get placeScooters => _currentMessages.generateStringAtIndex(623, []);

  String get placeSilkMaker => _currentMessages.generateStringAtIndex(624, []);

  String get placeTanjore => _currentMessages.generateStringAtIndex(625, []);

  String get placeThanjavurTemple =>
      _currentMessages.generateStringAtIndex(626, []);

  String rallyAccountAmount(
    String accountName,
    String accountNumber,
    String amount,
  ) =>
      _currentMessages
          .generateStringAtIndex(627, [accountName, accountNumber, amount]);

  String get rallyAccountDataCarSavings =>
      _currentMessages.generateStringAtIndex(628, []);

  String get rallyAccountDataChecking =>
      _currentMessages.generateStringAtIndex(629, []);

  String get rallyAccountDataHomeSavings =>
      _currentMessages.generateStringAtIndex(630, []);

  String get rallyAccountDataVacation =>
      _currentMessages.generateStringAtIndex(631, []);

  String get rallyAccountDetailDataAccountOwner =>
      _currentMessages.generateStringAtIndex(632, []);

  String get rallyAccountDetailDataAnnualPercentageYield =>
      _currentMessages.generateStringAtIndex(633, []);

  String get rallyAccountDetailDataInterestPaidLastYear =>
      _currentMessages.generateStringAtIndex(634, []);

  String get rallyAccountDetailDataInterestRate =>
      _currentMessages.generateStringAtIndex(635, []);

  String get rallyAccountDetailDataInterestYtd =>
      _currentMessages.generateStringAtIndex(636, []);

  String get rallyAccountDetailDataNextStatement =>
      _currentMessages.generateStringAtIndex(637, []);

  String get rallyAccountTotal =>
      _currentMessages.generateStringAtIndex(638, []);

  String get rallyAccounts => _currentMessages.generateStringAtIndex(639, []);

  String get rallyAlerts => _currentMessages.generateStringAtIndex(640, []);

  String rallyAlertsMessageATMFees(String amount) =>
      _currentMessages.generateStringAtIndex(641, [amount]);

  String rallyAlertsMessageCheckingAccount(String percent) =>
      _currentMessages.generateStringAtIndex(642, [percent]);

  String rallyAlertsMessageHeadsUpShopping(String percent) =>
      _currentMessages.generateStringAtIndex(643, [percent]);

  String rallyAlertsMessageSpentOnRestaurants(String amount) =>
      _currentMessages.generateStringAtIndex(644, [amount]);

  String rallyAlertsMessageUnassignedTransactions(int count) =>
      _currentMessages.generateStringAtIndex(645, [count]);

  String rallyBillAmount(
    String billName,
    String date,
    String amount,
  ) =>
      _currentMessages.generateStringAtIndex(646, [billName, date, amount]);

  String get rallyBillDetailAmountDue =>
      _currentMessages.generateStringAtIndex(647, []);

  String get rallyBillDetailAmountPaid =>
      _currentMessages.generateStringAtIndex(648, []);

  String get rallyBillDetailTotalAmount =>
      _currentMessages.generateStringAtIndex(649, []);

  String get rallyBills => _currentMessages.generateStringAtIndex(650, []);

  String get rallyBillsDue => _currentMessages.generateStringAtIndex(651, []);

  String rallyBudgetAmount(
    String budgetName,
    double amountUsed,
    double amountTotal,
    String amountLeft,
  ) =>
      _currentMessages.generateStringAtIndex(
          652, [budgetName, amountUsed, amountTotal, amountLeft]);

  String get rallyBudgetCategoryClothing =>
      _currentMessages.generateStringAtIndex(653, []);

  String get rallyBudgetCategoryCoffeeShops =>
      _currentMessages.generateStringAtIndex(654, []);

  String get rallyBudgetCategoryGroceries =>
      _currentMessages.generateStringAtIndex(655, []);

  String get rallyBudgetCategoryRestaurants =>
      _currentMessages.generateStringAtIndex(656, []);

  String get rallyBudgetDetailAmountLeft =>
      _currentMessages.generateStringAtIndex(657, []);

  String get rallyBudgetDetailAmountUsed =>
      _currentMessages.generateStringAtIndex(658, []);

  String get rallyBudgetDetailTotalCap =>
      _currentMessages.generateStringAtIndex(659, []);

  String get rallyBudgetLeft => _currentMessages.generateStringAtIndex(660, []);

  String get rallyBudgets => _currentMessages.generateStringAtIndex(661, []);

  String get rallyDescription =>
      _currentMessages.generateStringAtIndex(662, []);

  String get rallyFinanceLeft =>
      _currentMessages.generateStringAtIndex(663, []);

  String get rallyLoginButtonLogin =>
      _currentMessages.generateStringAtIndex(664, []);

  String get rallyLoginLabelLogin =>
      _currentMessages.generateStringAtIndex(665, []);

  String get rallyLoginLoginToRally =>
      _currentMessages.generateStringAtIndex(666, []);

  String get rallyLoginNoAccount =>
      _currentMessages.generateStringAtIndex(667, []);

  String get rallyLoginPassword =>
      _currentMessages.generateStringAtIndex(668, []);

  String get rallyLoginRememberMe =>
      _currentMessages.generateStringAtIndex(669, []);

  String get rallyLoginSignUp =>
      _currentMessages.generateStringAtIndex(670, []);

  String get rallyLoginUsername =>
      _currentMessages.generateStringAtIndex(671, []);

  String get rallySeeAll => _currentMessages.generateStringAtIndex(672, []);

  String get rallySeeAllAccounts =>
      _currentMessages.generateStringAtIndex(673, []);

  String get rallySeeAllBills =>
      _currentMessages.generateStringAtIndex(674, []);

  String get rallySeeAllBudgets =>
      _currentMessages.generateStringAtIndex(675, []);

  String get rallySettingsFindAtms =>
      _currentMessages.generateStringAtIndex(676, []);

  String get rallySettingsHelp =>
      _currentMessages.generateStringAtIndex(677, []);

  String get rallySettingsManageAccounts =>
      _currentMessages.generateStringAtIndex(678, []);

  String get rallySettingsNotifications =>
      _currentMessages.generateStringAtIndex(679, []);

  String get rallySettingsPaperlessSettings =>
      _currentMessages.generateStringAtIndex(680, []);

  String get rallySettingsPasscodeAndTouchId =>
      _currentMessages.generateStringAtIndex(681, []);

  String get rallySettingsPersonalInformation =>
      _currentMessages.generateStringAtIndex(682, []);

  String get rallySettingsSignOut =>
      _currentMessages.generateStringAtIndex(683, []);

  String get rallySettingsTaxDocuments =>
      _currentMessages.generateStringAtIndex(684, []);

  String get rallyTitleAccounts =>
      _currentMessages.generateStringAtIndex(685, []);

  String get rallyTitleBills => _currentMessages.generateStringAtIndex(686, []);

  String get rallyTitleBudgets =>
      _currentMessages.generateStringAtIndex(687, []);

  String get rallyTitleOverview =>
      _currentMessages.generateStringAtIndex(688, []);

  String get rallyTitleSettings =>
      _currentMessages.generateStringAtIndex(689, []);

  String get replyDescription =>
      _currentMessages.generateStringAtIndex(690, []);

  String get replyDraftsLabel =>
      _currentMessages.generateStringAtIndex(691, []);

  String get replyInboxLabel => _currentMessages.generateStringAtIndex(692, []);

  String get replySentLabel => _currentMessages.generateStringAtIndex(693, []);

  String get replySpamLabel => _currentMessages.generateStringAtIndex(694, []);

  String get replyStarredLabel =>
      _currentMessages.generateStringAtIndex(695, []);

  String get replyTrashLabel => _currentMessages.generateStringAtIndex(696, []);

  String get select => _currentMessages.generateStringAtIndex(697, []);

  String get selectable => _currentMessages.generateStringAtIndex(698, []);

  String get selected => _currentMessages.generateStringAtIndex(699, []);

  String get settingsAbout => _currentMessages.generateStringAtIndex(700, []);

  String get settingsAttribution =>
      _currentMessages.generateStringAtIndex(701, []);

  String get settingsButtonCloseLabel =>
      _currentMessages.generateStringAtIndex(702, []);

  String get settingsButtonLabel =>
      _currentMessages.generateStringAtIndex(703, []);

  String get settingsDarkTheme =>
      _currentMessages.generateStringAtIndex(704, []);

  String get settingsFeedback =>
      _currentMessages.generateStringAtIndex(705, []);

  String get settingsLightTheme =>
      _currentMessages.generateStringAtIndex(706, []);

  String get settingsLocale => _currentMessages.generateStringAtIndex(707, []);

  String get settingsPlatformMechanics =>
      _currentMessages.generateStringAtIndex(708, []);

  String get settingsSlowMotion =>
      _currentMessages.generateStringAtIndex(709, []);

  String get settingsSystemDefault =>
      _currentMessages.generateStringAtIndex(710, []);

  String get settingsTextDirection =>
      _currentMessages.generateStringAtIndex(711, []);

  String get settingsTextDirectionLTR =>
      _currentMessages.generateStringAtIndex(712, []);

  String get settingsTextDirectionLocaleBased =>
      _currentMessages.generateStringAtIndex(713, []);

  String get settingsTextDirectionRTL =>
      _currentMessages.generateStringAtIndex(714, []);

  String get settingsTextScaling =>
      _currentMessages.generateStringAtIndex(715, []);

  String get settingsTextScalingHuge =>
      _currentMessages.generateStringAtIndex(716, []);

  String get settingsTextScalingLarge =>
      _currentMessages.generateStringAtIndex(717, []);

  String get settingsTextScalingNormal =>
      _currentMessages.generateStringAtIndex(718, []);

  String get settingsTextScalingSmall =>
      _currentMessages.generateStringAtIndex(719, []);

  String get settingsTheme => _currentMessages.generateStringAtIndex(720, []);

  String get settingsTitle => _currentMessages.generateStringAtIndex(721, []);

  String get shrineCancelButtonCaption =>
      _currentMessages.generateStringAtIndex(722, []);

  String get shrineCartClearButtonCaption =>
      _currentMessages.generateStringAtIndex(723, []);

  String shrineCartItemCount(int quantity) =>
      _currentMessages.generateStringAtIndex(724, [quantity]);

  String get shrineCartPageCaption =>
      _currentMessages.generateStringAtIndex(725, []);

  String get shrineCartShippingCaption =>
      _currentMessages.generateStringAtIndex(726, []);

  String get shrineCartSubtotalCaption =>
      _currentMessages.generateStringAtIndex(727, []);

  String get shrineCartTaxCaption =>
      _currentMessages.generateStringAtIndex(728, []);

  String get shrineCartTotalCaption =>
      _currentMessages.generateStringAtIndex(729, []);

  String get shrineCategoryNameAccessories =>
      _currentMessages.generateStringAtIndex(730, []);

  String get shrineCategoryNameAll =>
      _currentMessages.generateStringAtIndex(731, []);

  String get shrineCategoryNameClothing =>
      _currentMessages.generateStringAtIndex(732, []);

  String get shrineCategoryNameHome =>
      _currentMessages.generateStringAtIndex(733, []);

  String get shrineDescription =>
      _currentMessages.generateStringAtIndex(734, []);

  String get shrineLoginPasswordLabel =>
      _currentMessages.generateStringAtIndex(735, []);

  String get shrineLoginUsernameLabel =>
      _currentMessages.generateStringAtIndex(736, []);

  String get shrineLogoutButtonCaption =>
      _currentMessages.generateStringAtIndex(737, []);

  String get shrineMenuCaption =>
      _currentMessages.generateStringAtIndex(738, []);

  String get shrineNextButtonCaption =>
      _currentMessages.generateStringAtIndex(739, []);

  String get shrineProductBlueStoneMug =>
      _currentMessages.generateStringAtIndex(740, []);

  String get shrineProductCeriseScallopTee =>
      _currentMessages.generateStringAtIndex(741, []);

  String get shrineProductChambrayNapkins =>
      _currentMessages.generateStringAtIndex(742, []);

  String get shrineProductChambrayShirt =>
      _currentMessages.generateStringAtIndex(743, []);

  String get shrineProductClassicWhiteCollar =>
      _currentMessages.generateStringAtIndex(744, []);

  String get shrineProductClaySweater =>
      _currentMessages.generateStringAtIndex(745, []);

  String get shrineProductCopperWireRack =>
      _currentMessages.generateStringAtIndex(746, []);

  String get shrineProductFineLinesTee =>
      _currentMessages.generateStringAtIndex(747, []);

  String get shrineProductGardenStrand =>
      _currentMessages.generateStringAtIndex(748, []);

  String get shrineProductGatsbyHat =>
      _currentMessages.generateStringAtIndex(749, []);

  String get shrineProductGentryJacket =>
      _currentMessages.generateStringAtIndex(750, []);

  String get shrineProductGiltDeskTrio =>
      _currentMessages.generateStringAtIndex(751, []);

  String get shrineProductGingerScarf =>
      _currentMessages.generateStringAtIndex(752, []);

  String get shrineProductGreySlouchTank =>
      _currentMessages.generateStringAtIndex(753, []);

  String get shrineProductHurrahsTeaSet =>
      _currentMessages.generateStringAtIndex(754, []);

  String get shrineProductKitchenQuattro =>
      _currentMessages.generateStringAtIndex(755, []);

  String get shrineProductNavyTrousers =>
      _currentMessages.generateStringAtIndex(756, []);

  String get shrineProductPlasterTunic =>
      _currentMessages.generateStringAtIndex(757, []);

  String shrineProductPrice(String price) =>
      _currentMessages.generateStringAtIndex(758, [price]);

  String shrineProductQuantity(int quantity) =>
      _currentMessages.generateStringAtIndex(759, [quantity]);

  String get shrineProductQuartetTable =>
      _currentMessages.generateStringAtIndex(760, []);

  String get shrineProductRainwaterTray =>
      _currentMessages.generateStringAtIndex(761, []);

  String get shrineProductRamonaCrossover =>
      _currentMessages.generateStringAtIndex(762, []);

  String get shrineProductSeaTunic =>
      _currentMessages.generateStringAtIndex(763, []);

  String get shrineProductSeabreezeSweater =>
      _currentMessages.generateStringAtIndex(764, []);

  String get shrineProductShoulderRollsTee =>
      _currentMessages.generateStringAtIndex(765, []);

  String get shrineProductShrugBag =>
      _currentMessages.generateStringAtIndex(766, []);

  String get shrineProductSootheCeramicSet =>
      _currentMessages.generateStringAtIndex(767, []);

  String get shrineProductStellaSunglasses =>
      _currentMessages.generateStringAtIndex(768, []);

  String get shrineProductStrutEarrings =>
      _currentMessages.generateStringAtIndex(769, []);

  String get shrineProductSucculentPlanters =>
      _currentMessages.generateStringAtIndex(770, []);

  String get shrineProductSunshirtDress =>
      _currentMessages.generateStringAtIndex(771, []);

  String get shrineProductSurfAndPerfShirt =>
      _currentMessages.generateStringAtIndex(772, []);

  String get shrineProductVagabondSack =>
      _currentMessages.generateStringAtIndex(773, []);

  String get shrineProductVarsitySocks =>
      _currentMessages.generateStringAtIndex(774, []);

  String get shrineProductWalterHenleyWhite =>
      _currentMessages.generateStringAtIndex(775, []);

  String get shrineProductWeaveKeyring =>
      _currentMessages.generateStringAtIndex(776, []);

  String get shrineProductWhitePinstripeShirt =>
      _currentMessages.generateStringAtIndex(777, []);

  String get shrineProductWhitneyBelt =>
      _currentMessages.generateStringAtIndex(778, []);

  String shrineScreenReaderCart(int quantity) =>
      _currentMessages.generateStringAtIndex(779, [quantity]);

  String get shrineScreenReaderProductAddToCart =>
      _currentMessages.generateStringAtIndex(780, []);

  String shrineScreenReaderRemoveProductButton(String product) =>
      _currentMessages.generateStringAtIndex(781, [product]);

  String get shrineTooltipCloseCart =>
      _currentMessages.generateStringAtIndex(782, []);

  String get shrineTooltipCloseMenu =>
      _currentMessages.generateStringAtIndex(783, []);

  String get shrineTooltipOpenMenu =>
      _currentMessages.generateStringAtIndex(784, []);

  String get shrineTooltipRemoveItem =>
      _currentMessages.generateStringAtIndex(785, []);

  String get shrineTooltipSearch =>
      _currentMessages.generateStringAtIndex(786, []);

  String get shrineTooltipSettings =>
      _currentMessages.generateStringAtIndex(787, []);

  String get signIn => _currentMessages.generateStringAtIndex(788, []);

  String get splashSelectDemo =>
      _currentMessages.generateStringAtIndex(789, []);

  String get starterAppDescription =>
      _currentMessages.generateStringAtIndex(790, []);

  String starterAppDrawerItem(int value) =>
      _currentMessages.generateStringAtIndex(791, [value]);

  String get starterAppGenericBody =>
      _currentMessages.generateStringAtIndex(792, []);

  String get starterAppGenericButton =>
      _currentMessages.generateStringAtIndex(793, []);

  String get starterAppGenericHeadline =>
      _currentMessages.generateStringAtIndex(794, []);

  String get starterAppGenericSubtitle =>
      _currentMessages.generateStringAtIndex(795, []);

  String get starterAppGenericTitle =>
      _currentMessages.generateStringAtIndex(796, []);

  String get starterAppTitle => _currentMessages.generateStringAtIndex(797, []);

  String get starterAppTooltipAdd =>
      _currentMessages.generateStringAtIndex(798, []);

  String get starterAppTooltipFavorite =>
      _currentMessages.generateStringAtIndex(799, []);

  String get starterAppTooltipSearch =>
      _currentMessages.generateStringAtIndex(800, []);

  String get starterAppTooltipShare =>
      _currentMessages.generateStringAtIndex(801, []);
}
