# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new internal build to Google Play"
  lane :internal do
    gradle(task: "clean")
    sh "flutter build appbundle"
    upload_to_play_store(
      track: 'internal',
      validate_only: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_CONFIG_JSON'],
      )
  end

  desc "Submit a new production build to Google Play"
  lane :prod do
    gradle(task: "clean")
    sh "flutter build appbundle"
    upload_to_play_store(
      validate_only: true,
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_CONFIG_JSON'],
    )
  end
end
